// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Chonye.Domain.Models;

public class Datum
{
    public int DataId { get; set; }

    public int UserId { get; set; }

    public string Data { get; set; } = null!;

    public Guid? GlobalId { get; set; }

    public virtual User User { get; set; } = null!;
}