// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Chonye.Domain.Models;

public class Subscription
{
    public int SubscriptionId { get; set; }

    public int TenantId { get; set; }

    public string SubscriptionType { get; set; } = null!;

    public DateTime StartDate { get; set; }

    public DateTime EndDate { get; set; }

    public Guid? GlobalId { get; set; }

    public virtual Tenant Tenant { get; set; } = null!;
}