// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Chonye.Domain.Interfaces;

namespace Chonye.Domain.Models;

public class Tenant : DomainModel
{
    public int TenantId { get; set; }

    public string Name { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string? Address { get; set; }

    public string? Phone { get; set; }


    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();

    public virtual ICollection<Usage> Usages { get; set; } = new List<Usage>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();
    public Guid GlobalId { get; set; }
}