// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Chonye.Domain.Models;

public partial class Usage
{
    public int UsageId { get; set; }

    public int TenantId { get; set; }

    public DateTime UsageDate { get; set; }

    public string UsageType { get; set; } = null!;

    public string? UsageDetails { get; set; }

    public Guid? GlobalId { get; set; }

    public virtual Tenant Tenant { get; set; } = null!;
}